"use client";
import { SessionProvider } from 'next-auth/react';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, ...props }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
        
        {children}
        </SessionProvider>
       </body>
    </html>
  )
}
